<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net8.0\AddUser.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net8.0\AddUser.GlobalUsings.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0\AddUser.deps.json" />
    <Content Include="bin\Debug\net8.0\AddUser.runtimeconfig.json" />
    <Content Include="obj\AddUser.csproj.nuget.dgspec.json" />
    <Content Include="obj\Debug\net8.0\AddUser.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net8.0\AddUser.sourcelink.json" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net8.0\AddUser.dll" />
    <None Include="bin\Debug\net8.0\AddUser.dll.config" />
    <None Include="bin\Debug\net8.0\AddUser.exe" />
    <None Include="bin\Debug\net8.0\AddUser.pdb" />
    <None Include="bin\Debug\net8.0\de\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\es\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\fr\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\it\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\ja\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\ko\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\Microsoft.IdentityModel.Abstractions.dll" />
    <None Include="bin\Debug\net8.0\Microsoft.IdentityModel.Logging.dll" />
    <None Include="bin\Debug\net8.0\Microsoft.IdentityModel.Protocols.dll" />
    <None Include="bin\Debug\net8.0\Microsoft.IdentityModel.Tokens.dll" />
    <None Include="bin\Debug\net8.0\Microsoft.SqlServer.Server.dll" />
    <None Include="bin\Debug\net8.0\Microsoft.SqlServer.Types.dll" />
    <None Include="bin\Debug\net8.0\pt-BR\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\runtimes\unix\lib\net8.0\System.Data.SqlClient.dll" />
    <None Include="bin\Debug\net8.0\runtimes\win-arm64\native\sni.dll" />
    <None Include="bin\Debug\net8.0\runtimes\win-x64\native\sni.dll" />
    <None Include="bin\Debug\net8.0\runtimes\win-x64\native\SqlServerSpatial160.dll" />
    <None Include="bin\Debug\net8.0\runtimes\win-x86\native\sni.dll" />
    <None Include="bin\Debug\net8.0\runtimes\win-x86\native\SqlServerSpatial160.dll" />
    <None Include="bin\Debug\net8.0\runtimes\win\lib\net8.0\System.Data.SqlClient.dll" />
    <None Include="bin\Debug\net8.0\runtimes\win\lib\net8.0\System.Diagnostics.EventLog.dll" />
    <None Include="bin\Debug\net8.0\runtimes\win\lib\net8.0\System.Diagnostics.EventLog.Messages.dll" />
    <None Include="bin\Debug\net8.0\ru\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\System.Configuration.ConfigurationManager.dll" />
    <None Include="bin\Debug\net8.0\System.Data.SqlClient.dll" />
    <None Include="bin\Debug\net8.0\System.Diagnostics.EventLog.dll" />
    <None Include="bin\Debug\net8.0\System.Security.Cryptography.ProtectedData.dll" />
    <None Include="bin\Debug\net8.0\zh-Hans\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="bin\Debug\net8.0\zh-Hant\Microsoft.SqlServer.Types.resources.dll" />
    <None Include="obj\AddUser.csproj.nuget.g.props" />
    <None Include="obj\AddUser.csproj.nuget.g.targets" />
    <None Include="obj\Debug\net8.0\AddUser.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net8.0\AddUser.assets.cache" />
    <None Include="obj\Debug\net8.0\AddUser.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net8.0\AddUser.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net8.0\AddUser.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net8.0\AddUser.csproj.Up2Date" />
    <None Include="obj\Debug\net8.0\AddUser.dll" />
    <None Include="obj\Debug\net8.0\AddUser.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net8.0\AddUser.genruntimeconfig.cache" />
    <None Include="obj\Debug\net8.0\AddUser.pdb" />
    <None Include="obj\Debug\net8.0\apphost.exe" />
    <None Include="obj\Debug\net8.0\refint\AddUser.dll" />
    <None Include="obj\Debug\net8.0\ref\AddUser.dll" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="7.7.1" />
    <PackageReference Include="Microsoft.SqlServer.Server" Version="1.0.0" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

</Project>
