//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCTemp
{
    public partial class Apply
    {
        protected global::System.Web.UI.WebControls.Panel pnlSearch;

        protected global::System.Web.UI.WebControls.TextBox txtSearchTitle;

        protected global::System.Web.UI.WebControls.TextBox txtSearchLocation;

        protected global::System.Web.UI.WebControls.Button btnSearchJobs;

        protected global::System.Web.UI.WebControls.GridView grdSearchResults;

        protected global::System.Web.UI.WebControls.Panel pnlApply;

        protected global::System.Web.UI.WebControls.HiddenField hfJobId;

        protected global::System.Web.UI.WebControls.Label lblJobTitle;

        protected global::System.Web.UI.WebControls.Label lblUploadError;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.TextBox txtCover;

        protected global::System.Web.UI.WebControls.FileUpload fuResume;

        protected global::System.Web.UI.WebControls.Button btnSubmit;

        protected global::System.Web.UI.WebControls.Label lblResult;
    }
}
