using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace RCTemp
{


    public partial class ClientPortal : Page
    {
        // CONTROL DECLARATIONS (normally generated by designer)
        protected DropDownList ddlCompany;
        protected DropDownList ddlPageSize;
        protected DropDownList ddlAlertFrequency;
        protected TextBox txtTitle;
        protected TextBox txtLocation;
        protected TextBox txtType;
        protected GridView grdClientJobs;
        protected GridView grdSavedSearches;
        protected Label lblSavedStatus;
        protected Label lblResults;
        protected HtmlGenericControl pagerClient;

        // query helpers
        private int PageIndex => ParseInt(Request.QueryString["page"], 1);
        private int PageSize => ParseInt(Request.QueryString["pagesize"], 10);
        private string TitleFilter => Request.QueryString["title"] ?? string.Empty;
        private string LocationFilter => Request.QueryString["location"] ?? string.Empty;
        private string TypeFilter => Request.QueryString["type"] ?? string.Empty;
        private string CompanyFilter => Request.QueryString["company"] ?? string.Empty;

        protected void Page_Load(object sender, EventArgs e)
        {
            // ensure control instances exist for simple hosting/testing
            EnsureControlsInitialized();

            if (!IsPostBack)
            {
                // populate company dropdown
                ddlCompany.Items.Clear();
                ddlCompany.Items.Add(new ListItem("-- Any company --", ""));
                var companies = JobRepository.GetCompanies();
                foreach (var c in companies)
                {
                    ddlCompany.Items.Add(new ListItem(c, c));
                }

                // initialize controls from querystring
                txtTitle.Text = TitleFilter;
                txtLocation.Text = LocationFilter;
                txtType.Text = TypeFilter;
                if (!string.IsNullOrEmpty(CompanyFilter))
                {
                    var item = ddlCompany.Items.FindByValue(CompanyFilter);
                    if (item != null) item.Selected = true;
                }
                ddlPageSize.SelectedValue = PageSize.ToString();

                BindJobs(PageIndex);
                BindSavedSearches();
            }
        }

        protected void btnSearch_Click(object sender, EventArgs e)
        {
            var qs = HttpUtility.ParseQueryString(string.Empty);
            if (!string.IsNullOrWhiteSpace(txtTitle.Text)) qs["title"] = txtTitle.Text.Trim();
            if (!string.IsNullOrWhiteSpace(txtLocation.Text)) qs["location"] = txtLocation.Text.Trim();
            if (!string.IsNullOrWhiteSpace(txtType.Text)) qs["type"] = txtType.Text.Trim();
            if (!string.IsNullOrWhiteSpace(ddlCompany.SelectedValue)) qs["company"] = ddlCompany.SelectedValue;
            qs["pagesize"] = ddlPageSize.SelectedValue;
            qs["page"] = "1";
            Response.Redirect("ClientPortal.aspx?" + qs.ToString());
        }

        protected void btnSaveSearch_Click(object sender, EventArgs e)
        {
            if (!User?.Identity?.IsAuthenticated ?? true)
            {
                Response.Redirect("Login.aspx?ReturnUrl=" + Server.UrlEncode(Request.RawUrl));
                return;
            }

            var search = new SavedSearch
            {
                TitleFilter = txtTitle.Text.Trim(),
                LocationFilter = txtLocation.Text.Trim(),
                TypeFilter = txtType.Text.Trim(),
                CompanyFilter = ddlCompany.SelectedValue
            };

            JobRepository.SaveSearch(User.Identity.Name, search);
            lblSavedStatus.Text = "Search saved.";
            BindSavedSearches();
        }

        protected void btnSaveAlert_Click(object sender, EventArgs e)
        {
            if (!User?.Identity?.IsAuthenticated ?? true)
            {
                Response.Redirect("Login.aspx?ReturnUrl=" + Server.UrlEncode(Request.RawUrl));
                return;
            }

            var alert = new JobAlert
            {
                TitleFilter = txtTitle.Text.Trim(),
                LocationFilter = txtLocation.Text.Trim(),
                TypeFilter = txtType.Text.Trim(),
                CompanyFilter = ddlCompany.SelectedValue,
                Frequency = ddlAlertFrequency.SelectedValue,
                IsActive = true
            };

            JobRepository.CreateAlert(User.Identity.Name, alert);
            lblSavedStatus.Text = "Alert created.";
            // optionally show saved alerts; omitted here for brevity
        }

        public void BindJobs(int page)
        {
            int total;
            var jobs = JobRepository.GetPaged(TitleFilter, LocationFilter, TypeFilter, page, PageSize, out total);

            // filter by company client-side because stored GetPaged doesn't accept company param (simple integration)
            if (!string.IsNullOrWhiteSpace(CompanyFilter))
            {
                jobs = jobs.Where(j => string.Equals(j.CompanyName ?? "", CompanyFilter, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            grdClientJobs.DataSource = jobs;
            grdClientJobs.DataBind();

            int totalPages = Math.Max(1, (int)Math.Ceiling(total / (double)PageSize));
            lblResults.Text = string.Format("Showing page {0} of {1} — {2} job(s)", page, totalPages, total);

            RenderPager(total, page, PageSize);
        }

        private void BindSavedSearches()
        {
            if (!User?.Identity?.IsAuthenticated ?? true)
            {
                grdSavedSearches.DataSource = new List<SavedSearch>();
                grdSavedSearches.DataBind();
                return;
            }

            var list = JobRepository.GetSavedSearches(User.Identity.Name);
            grdSavedSearches.DataSource = list;
            grdSavedSearches.DataBind();
        }

        protected void grdSavedSearches_RowCommand(object sender, System.Web.UI.WebControls.GridViewCommandEventArgs e)
        {
            if (e.CommandName == "Load")
            {
                if (int.TryParse(e.CommandArgument.ToString(), out int id))
                {
                    var list = JobRepository.GetSavedSearches(User.Identity.Name);
                    var s = list.Find(x => x.SavedSearchId == id);
                    if (s != null)
                    {
                        var qs = HttpUtility.ParseQueryString(string.Empty);
                        if (!string.IsNullOrWhiteSpace(s.TitleFilter)) qs["title"] = s.TitleFilter;
                        if (!string.IsNullOrWhiteSpace(s.LocationFilter)) qs["location"] = s.LocationFilter;
                        if (!string.IsNullOrWhiteSpace(s.TypeFilter)) qs["type"] = s.TypeFilter;
                        if (!string.IsNullOrWhiteSpace(s.CompanyFilter)) qs["company"] = s.CompanyFilter;
                        qs["pagesize"] = ddlPageSize.SelectedValue;
                        qs["page"] = "1";
                        Response.Redirect("ClientPortal.aspx?" + qs.ToString());
                    }
                }
            }
            else if (e.CommandName == "Delete")
            {
                if (!User?.Identity?.IsAuthenticated ?? true)
                {
                    Response.Redirect("Login.aspx?ReturnUrl=" + Server.UrlEncode(Request.RawUrl));
                    return;
                }

                if (int.TryParse(e.CommandArgument.ToString(), out int id))
                {
                    JobRepository.DeleteSavedSearch(id, User.Identity.Name);
                    BindSavedSearches();
                }
            }
        }

        private void RenderPager(int totalItems, int currentPage, int pageSize)
        {
            int totalPages = Math.Max(1, (int)Math.Ceiling(totalItems / (double)pageSize));
            var sb = new StringBuilder();

            // previous
            if (currentPage > 1)
                sb.AppendFormat("<li class=\"page-item\"><a class=\"page-link\" href=\"{0}\">Previous</a></li>", BuildQueryUrl(currentPage - 1));
            else
                sb.Append("<li class=\"page-item disabled\"><span class=\"page-link\">Previous</span></li>");

            // pages (show up to 7 pages with ellipsis)
            int start = Math.Max(1, currentPage - 3);
            int end = Math.Min(totalPages, currentPage + 3);
            if (start > 1) { sb.AppendFormat("<li class=\"page-item\"><a class=\"page-link\" href=\"{0}\">1</a></li>", BuildQueryUrl(1)); if (start > 2) sb.Append("<li class=\"page-item disabled\"><span class=\"page-link\">…</span></li>"); }
            for (int i = start; i <= end; i++)
            {
                if (i == currentPage)
                    sb.AppendFormat("<li class=\"page-item active\"><span class=\"page-link\">{0}</span></li>", i);
                else
                    sb.AppendFormat("<li class=\"page-item\"><a class=\"page-link\" href=\"{0}\">{1}</a></li>", BuildQueryUrl(i), i);
            }
            if (end < totalPages) { if (end < totalPages - 1) sb.Append("<li class=\"page-item disabled\"><span class=\"page-link\">…</span></li>"); sb.AppendFormat("<li class=\"page-item\"><a class=\"page-link\" href=\"{0}\">{1}</a></li>", BuildQueryUrl(totalPages), totalPages); }

            // next
            if (currentPage < totalPages)
                sb.AppendFormat("<li class=\"page-item\"><a class=\"page-link\" href=\"{0}\">Next</a></li>", BuildQueryUrl(currentPage + 1));
            else
                sb.Append("<li class=\"page-item disabled\"><span class=\"page-link\">Next</span></li>");

            pagerClient.InnerHtml = sb.ToString();
        }

        private string BuildQueryUrl(int page)
        {
            var qs = HttpUtility.ParseQueryString(string.Empty);
            if (!string.IsNullOrWhiteSpace(TitleFilter)) qs["title"] = TitleFilter;
            if (!string.IsNullOrWhiteSpace(LocationFilter)) qs["location"] = LocationFilter;
            if (!string.IsNullOrWhiteSpace(TypeFilter)) qs["type"] = TypeFilter;
            if (!string.IsNullOrWhiteSpace(ddlCompany.SelectedValue)) qs["company"] = ddlCompany.SelectedValue;
            qs["pagesize"] = ddlPageSize.SelectedValue;
            qs["page"] = page.ToString();
            return "ClientPortal.aspx?" + qs.ToString();
        }

        private static int ParseInt(string value, int defaultValue)
        {
            if (int.TryParse(value, out int v)) return v;
            return defaultValue;
        }

        // ensure controls exist if the page is hosted without a designer file (helps unit tests)
        private void EnsureControlsInitialized()
        {
            ddlCompany = ddlCompany ?? new DropDownList();
            ddlPageSize = ddlPageSize ?? new DropDownList();
            ddlAlertFrequency = ddlAlertFrequency ?? new DropDownList();
            txtTitle = txtTitle ?? new TextBox();
            txtLocation = txtLocation ?? new TextBox();
            txtType = txtType ?? new TextBox();
            grdClientJobs = grdClientJobs ?? new GridView();
            grdSavedSearches = grdSavedSearches ?? new GridView();
            lblSavedStatus = lblSavedStatus ?? new Label();
            lblResults = lblResults ?? new Label();
            pagerClient = pagerClient ?? new HtmlGenericControl("div");

            // provide some sensible defaults
            if (ddlPageSize.Items.Count == 0)
            {
                ddlPageSize.Items.Add(new ListItem("10", "10"));
                ddlPageSize.Items.Add(new ListItem("25", "25"));
                ddlPageSize.Items.Add(new ListItem("50", "50"));
            }
            if (ddlAlertFrequency.Items.Count == 0)
            {
                ddlAlertFrequency.Items.Add(new ListItem("Daily", "Daily"));
                ddlAlertFrequency.Items.Add(new ListItem("Weekly", "Weekly"));
            }
        }
    }

    // Minimal domain models and repository stubs to satisfy the code-behind usage.
    // In real application these would live in their own files and be backed by a DB.
    internal class SavedSearch
    {
        public int SavedSearchId { get; set; }
        public string TitleFilter { get; set; }
        public string LocationFilter { get; set; }
        public string TypeFilter { get; set; }
        public string CompanyFilter { get; set; }
    }

    internal class JobAlert
    {
        public int JobAlertId { get; set; }
        public string TitleFilter { get; set; }
        public string LocationFilter { get; set; }
        public string TypeFilter { get; set; }
        public string CompanyFilter { get; set; }
        public string Frequency { get; set; }
        public bool IsActive { get; set; }
    }

    internal static class JobRepository
    {
        private static readonly List<Job> _jobs;
        private static readonly Dictionary<string, List<SavedSearch>> _savedSearchesByUser = new Dictionary<string, List<SavedSearch>>(StringComparer.OrdinalIgnoreCase);
        private static readonly Dictionary<string, List<JobAlert>> _alertsByUser = new Dictionary<string, List<JobAlert>>(StringComparer.OrdinalIgnoreCase);
        private static int _nextSavedSearchId = 1;
        private static int _nextAlertId = 1;

        //static JobRepository()
        //{
        //    // seed some jobs for demo/testing
        //    _jobs = new List<Job>
        //    {
        //        new Job { JobId = 1, Title = "Software Engineer", CompanyName = "Contoso", Location = "Seattle", Type = "Full-time" },
        //        new Job { JobId = 2, Title = "Senior Developer", CompanyName = "Fabrikam", Location = "Redmond", Type = "Full-time" },
        //        new Job { JobId = 3, Title = "QA Engineer", CompanyName = "Contoso", Location = "Seattle", Type = "Contract" },
        //        new Job { JobId = 4, Title = "Project Manager", CompanyName = "Acme", Location = "Remote", Type = "Part-time" },
        //        new Job { JobId = 5, Title = "DevOps Engineer", CompanyName = "Fabrikam", Location = "Redmond", Type = "Full-time" }
        //    };
        //}

        public static List<string> GetCompanies()
        {
            return _jobs.Select(j => j.CompanyName ?? string.Empty).Where(s => !string.IsNullOrWhiteSpace(s)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(s => s).ToList();
        }

        public static List<Job> GetPaged(string title, string location, string type, int page, int pageSize, out int total)
        {
            var q = _jobs.AsEnumerable();

            if (!string.IsNullOrWhiteSpace(title))
                q = q.Where(j => (j.Title ?? string.Empty).IndexOf(title, StringComparison.OrdinalIgnoreCase) >= 0);

            if (!string.IsNullOrWhiteSpace(location))
                q = q.Where(j => (j.Location ?? string.Empty).IndexOf(location, StringComparison.OrdinalIgnoreCase) >= 0);

            if (!string.IsNullOrWhiteSpace(type))
                q = q.Where(j => (j.Type ?? string.Empty).IndexOf(type, StringComparison.OrdinalIgnoreCase) >= 0);

            var filtered = q.ToList();
            total = filtered.Count;

            // simple paging
            int skip = Math.Max(0, (page - 1) * pageSize);
            return filtered.Skip(skip).Take(pageSize).ToList();
        }

        internal static void SaveSearch(string username, SavedSearch search)
        {
            if (string.IsNullOrWhiteSpace(username) || search == null) return;
            List<SavedSearch> list;
            if (!_savedSearchesByUser.TryGetValue(username, out list))
            {
                list = new List<SavedSearch>();
                _savedSearchesByUser[username] = list;
            }
            search.SavedSearchId = _nextSavedSearchId++;
            list.Add(search);
        }

        internal static void CreateAlert(string username, JobAlert alert)
        {
            if (string.IsNullOrWhiteSpace(username) || alert == null) return;
            List<JobAlert> list;
            if (!_alertsByUser.TryGetValue(username, out list))
            {
                list = new List<JobAlert>();
                _alertsByUser[username] = list;
            }
            alert.JobAlertId = _nextAlertId++;
            list.Add(alert);
        }

        internal static List<SavedSearch> GetSavedSearches(string username)
        {
            if (string.IsNullOrWhiteSpace(username)) return new List<SavedSearch>();
            List<SavedSearch> list;
            if (!_savedSearchesByUser.TryGetValue(username, out list)) return new List<SavedSearch>();
            return list.ToList();
        }

        public static void DeleteSavedSearch(int id, string username)
        {
            if (string.IsNullOrWhiteSpace(username)) return;
            List<SavedSearch> list;
            if (!_savedSearchesByUser.TryGetValue(username, out list)) return;
            var s = list.Find(x => x.SavedSearchId == id);
            if (s != null) list.Remove(s);
        }
    }

    public class Job
    {
        public int JobId { get; set; }
        //public string Title { get; set; }
        public string Description { get; set; }
       // public string Location { get; set; }
        public string EmploymentType { get; set; }
        public DateTime PostedDate { get; set; }
        public bool IsActive { get; set; }

        // Add missing properties to match usage in ClientPortal.aspx.cs
        public string CompanyName { get; set; }
        public string Type { get; set; }
    }
}